# use php-apache official image
FROM php:8.3-apache

# run mysqli
RUN docker-php-ext-install mysqli

# set working directory
WORKDIR /var/www/html/

# copy all file from local directory to working directory
COPY . .